# Site settings
title: 谷雨书苑
header-img: img/home-bg.jpg
email: valleyrain.org@gmail.com
description: "谷雨书苑是一个立足于美国旧金山硅谷，面向广大华人的，自发性的非营利读书分享团体。 我们每周日会在线下分享讨论一本书。分享的内容涵盖人文，社科，历史，经济，商业金融等各个领域，以及跟书籍相关的电影，音乐，绘画等等。"
baseurl: ""
url: "http://www.valleyrain.org"
twitter_username: valleyrainbook
github_username:  valleyrain-org
facebook_username:  valleyrainbook

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
include: ['_pages']
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Data files URL
www-data-url: "https://raw.githubusercontent.com/valleyrain-org/www-data/master"

gems:
    - jekyll-sitemap
    - jekyll-redirect-from
